#pragma config(Sensor, S1,     lightSensor,    sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1 == 1) // Keeps loops going at a constant so repeats occur
{
	while(SensorValue(lightSensor) <= 9) // Thersehold value
	{
			motor[motorA] = 0; // Foward left motion
			motor[motorD] = 80;

	while(SensorValue(lightSensor) > 9){
			motor[motorA] = 80; // Foward rightmotion
			motor[motorD] = 0;
	}
}
}
