#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1==1){
	if (SensorValue(sonarSensor) >= 10) //A loop which keeps the motors running until the distacne on the sensor is less than 10 cm (May need to increase)
{
		motor[motorA] = 50;
		motor[motorD] = 50;
	}
	if (SensorValue(sonarSensor) < 10){
		motor[motorA] = -50; //The else statement will reverse the motors at the same speed they were going fotward
		motor[motorD] = -50;
		wait1Msec(500);
		break;
}
}
}
