#pragma config(Sensor, S3,     touchSensor,    sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(touchSensor) == 0) // D is right, A is left
	{
		motor[motorA] = 100;
		motor[motorD] = 100;
	}
	motor[motorA] = -60;
	motor[motorD] = -60;

	wait1Msec(1000);

		motor[motorA] = -10;
		motor[motorD] = 50;

		wait1Msec(700);
}
